const SpaceTypes = {
  agricultural: ["farm", "orchard", "ranch"],
  commercial: ["office", "restaurant", "retail", "showroom", "storefront"],
  hospitality: [
    "casino",
    "event-space",
    "hostel",
    "hotel",
    "motel",
    "resort",
    "shortlets",
    "timeshare",
  ],
  industrial: ["factory", "warehouse"],
  land: ["agricultural", "commercial", "residential", "mixed"],
  mixed: [
    "hotel-residential-complex",
    "lifestyle",
    "office-retail-complex",
    "residential-commercial-complex",
  ],
  recreational: [
    "arena",
    "amusement-park",
    "art",
    "concert",
    "garden",
    "gymnasium",
    "museum",
    "outdoor-park",
    "sports-complex",
    "stadium",
    "theater",
  ],
  residential: [
    "apartment",
    "condominium",
    "cottage",
    "bungalow",
    "detached",
    "duplex",
    "flat",
    "maisonette",
    "penthouse",
    "semi-detached",
    "studio",
    "townhouse",
    "villa",
  ],
  special: [
    "consulate",
    "data-center",
    "embassy",
    "educational",
    "government",
    "hospital",
    "laboratory",
    "religious",
    "research",
  ],
};

export default SpaceTypes;
