org: clair99

app: ahia

service: tourCron

frameworkVersion: "4"

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: af-south-1
  memorySize: 512

functions:
  ahia-tour-service-cron:
    handler: handler.cron
    events:
      - eventBridge:
          eventBus: ${env:AWS_DEFAULT_EVENT_BUS}
          pattern:
            source:
              - aws
    environment:
      NODE_ENV: ${env:NODE_ENV}
      MONGO_URI: ${env:MONGO_URI}
      TOUR_NOTIFICATION_EMAIL: ${env:TOUR_NOTIFICATION_EMAIL}
      TOUR_ADMIN_EMAIL_I: ${env:TOUR_ADMIN_EMAIL_I}
      TOUR_ADMIN_EMAIL_II: ${env:TOUR_ADMIN_EMAIL_II}
      TOUR_ADMIN_EMAIL_III: ${env:TOUR_ADMIN_EMAIL_III}
