AWSTemplateFormatVersion: "2010-09-09"

Description: ahia listing service expiry cron.

Parameters:
  AWSRegion:
    Type: String
    Default: "af-south-1"
  AWSDefaultEventBus:
    Type: String
  NodeEnv:
    Type: String
  MongoUri:
    Type: String
  ListingNotificationEmail:
    Type: String
  ListingAdminEmailI:
    Type: String

Resources:
  AhiaListingServiceExpiryCronFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: "ahia-listing-service-expiry-cron"
      Handler: "handler.cron"
      Runtime: "nodejs20.x"
      MemorySize: 512
      Environment:
        Variables:
          NODE_ENV: !Ref NodeEnv
          MONGO_URI: !Ref MongoUri
          LISTING_NOTIFICATION_EMAIL: !Ref ListingNotificationEmail
          LISTING_ADMIN_EMAIL_I: !Ref ListingAdminEmailI
      Role: !GetAtt AhiaListingServiceExpiryCronRole.Arn
      Code:
        S3Bucket: " "
        S3Key: " "

  AhiaListingServiceExpiryCronRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "ahia-listing-service-expiry-cron-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
              - Effect: "Allow"
                Action: "events:PutEvents"
                Resource: "*"

  AhiaListingServiceExpiryCronRule:
    Type: "AWS::Events::Rule"
    Properties:
      EventBusName: !Ref AWSDefaultEventBus
      EventPattern:
        source:
          - "aws"
      Targets:
        - Arn: !GetAtt AhiaListingServiceExpiryCronFunction.Arn
          Id: "AhiaListingServiceExpiryCronTarget"

  AhiaListingServiceExpiryCronPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref AhiaListingServiceExpiryCronFunction
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt AhiaListingServiceExpiryCronRule.Arn
