enum HttpStatus {
  OK = "OK",
  CREATED = "CREATED",
  MODIFIED = "MODIFIED",
  REDIRECT = "REDIRECT",
  BAD_REQUEST = "BADREQUEST",
  UNAUTHORISED = "UNAUTHORISED",
  PAYMENT_REQUIRED = "PAYMENTREQUIRED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOTFOUND",
  NOT_ALLOWED = "NOTALLOWED",
  CONFLICT = "CONFLICT",
  UNPROCESSABLE_ENTITY = "UNPROCESSABLEENTITY",
  INTERNAL_SERVER_ERROR = "INTERNALSERVERERROR",
  SERVICE_UNAVAILABLE = "SERVICEUNAVAILABLE",
}

export default HttpStatus;
