enum HttpStatus {
  OK = "OK",
  CREATED = "CREATED",
  MODIFIED = "MODIFIED",
  REDIRECT = "REDIRECT",
  BAD_REQUEST = "BAD REQUEST",
  UNAUTHORISED = "UNAUTHORISED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT FOUND",
  NOT_ALLOWED = "NOT ALLOWED",
  CONFLICT = "CONFLICT",
  PAYMENT_REQUIRED = "PAYMENT_REQUIRED",
  UNPROCESSABLE_ENTITY = "UNPROCESSABLE ENTITY",
  INTERNAL_SERVER_ERROR = "INTERNAL SERVER ERROR",
}

export default HttpStatus;
