org: clair99

app: ahia

service: provider

frameworkVersion: "4"

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION}
  memorySize: 512

functions:
  ahia-provider-api:
    handler: handler.provider
    events:
      - httpApi: "*"
    environment:
      NODE_ENV: ${env:NODE_ENV}
      MONGO_URI: ${env:MONGO_URI}
